"""
AdaMC Evaluation Script.

Computes two sets of metrics from a score.txt file generated by
experiments/text_generation/evaluate_watermark_score.py:

1. Zero-bit detection metrics (for comparing with MCMark):
   - Weighted z-score under H0 (CLT-based)
   - TPR @ FPR = threshold
   - Median p-value

2. Multi-bit message extraction accuracy:
   - Per-bit accuracy
   - Full-message accuracy (all bits correct)
   - Average bits embedded per token (embedding efficiency)

Usage:
    python ./evaluations/get_adamc_acc.py \\
        --score_path ./results/mmw_book_report/.../adamc/score.txt \\
        --fpr_thres 0.001 \\
        --message_hex 9a3bf201   # the 4-byte (32-bit) demo message in hex

For the demo message embedded by default in common.py:
    import hashlib
    demo_msg = hashlib.sha256(b"demo_user_42").digest()[:4]
    print(demo_msg.hex())
"""

import json
import os
import math
import argparse
import numpy as np
from collections import defaultdict
import scipy.stats as stats


# ---------------------------------------------------------------------------
# Zero-bit detection helpers
# ---------------------------------------------------------------------------

def compute_weighted_pvalue_from_lists(match_flags, n_t_list):
    """
    Compute the weighted detection p-value for one sample.

    S = sum_t w_t * X_t,  w_t = log2(n_t),  X_t = match_flag
    E[S|H0] = sum_t w_t / n_t
    Var[S|H0] = sum_t w_t^2 * (1/n_t) * (1 - 1/n_t)
    Z ~ N(0,1) under H0 by CLT
    p = P(Z >= z_obs | H0) = 1 - Phi(z_obs)

    Only tokens with n_t > 1 are counted.
    """
    S = 0.0
    E_S = 0.0
    Var_S = 0.0
    for x, n in zip(match_flags, n_t_list):
        if n <= 1:
            continue
        w = math.log2(n)
        S     += w * x
        E_S   += w / n
        Var_S += (w ** 2) * (1.0 / n) * (1.0 - 1.0 / n)

    if Var_S < 1e-10:
        return 0.0, 1.0, S

    z = (S - E_S) / math.sqrt(Var_S)
    p = stats.norm.sf(z)
    return z, p, S


# ---------------------------------------------------------------------------
# Multi-bit message extraction helpers
# ---------------------------------------------------------------------------

def bytes_to_bits(data: bytes):
    bits = []
    for byte in data:
        for i in range(7, -1, -1):
            bits.append((byte >> i) & 1)
    return bits


def bit_accuracy(extracted_bits, ground_truth_bits):
    """
    Compute per-bit accuracy given extracted bits and the ground truth message
    (cyclic).

    Args:
        extracted_bits: flat list of 0/1 recovered from a single text.
        ground_truth_bits: the embedded message bit list (may be shorter).

    Returns:
        accuracy: float in [0, 1].
    """
    if len(extracted_bits) == 0:
        return None  # no bits extracted (all low-entropy text)

    correct = 0
    total = len(extracted_bits)
    for i, b in enumerate(extracted_bits):
        expected = ground_truth_bits[i % len(ground_truth_bits)]
        correct += int(b == expected)
    return correct / total


def full_message_accuracy(extracted_bits, ground_truth_bits):
    """
    Check if the first len(ground_truth_bits) extracted bits exactly match
    the ground truth message.

    Returns:
        1 if perfect match, 0 otherwise, None if too few bits extracted.
    """
    L = len(ground_truth_bits)
    if len(extracted_bits) < L:
        return None
    for i in range(L):
        if extracted_bits[i] != ground_truth_bits[i]:
            return 0
    return 1


# ---------------------------------------------------------------------------
# Main evaluation
# ---------------------------------------------------------------------------

def generate_result(score_path, save_path, fpr_thres, len_limit, message_hex):
    """Read score.txt, compute all metrics, write to save_path."""

    # Decode ground-truth message
    if message_hex is not None:
        gt_bytes = bytes.fromhex(message_hex)
    else:
        import hashlib
        gt_bytes = hashlib.sha256(b"demo_user_42").digest()[:4]
    gt_bits = bytes_to_bits(gt_bytes)

    with open(score_path, "r") as f:
        lines = f.readlines()

    # Aggregation containers
    # Keyed by repr-string of the watermark processor
    p_value_list    = defaultdict(list)
    tpr_cnt         = defaultdict(int)
    tot_cnt         = defaultdict(int)
    bit_acc_list    = defaultdict(list)
    msg_acc_list    = defaultdict(list)
    bits_per_tok_list = defaultdict(list)

    for line in lines:
        res = json.loads(line)
        wp  = res.get("watermark_processor", "unknown")
        if "AdaMC_Reweight" not in wp:
            continue

        cur_len = res.get("lens", 0)
        if isinstance(cur_len, list):
            cur_len = cur_len[0]
        if cur_len < len_limit:
            continue

        match_flags = res.get("match_flags", [])
        n_t_list    = res.get("n_t_list",    [])
        extracted   = res.get("extracted_bits", [])
        # Fields are stored as JSON strings (to satisfy simple_store_worker constraints)
        if isinstance(match_flags, str):
            match_flags = json.loads(match_flags)
        if isinstance(n_t_list, str):
            n_t_list = json.loads(n_t_list)
        if isinstance(extracted, str):
            extracted = json.loads(extracted)
        # Trim leading zeros (first 2 tokens are masked)
        match_flags = [m for m, n in zip(match_flags, n_t_list) if n > 1]
        n_t_list    = [n for n in n_t_list if n > 1]

        if len(match_flags) == 0:
            continue

        _, p_val, _ = compute_weighted_pvalue_from_lists(match_flags, n_t_list)
        p_value_list[wp].append(p_val)
        tot_cnt[wp] += 1
        if p_val <= fpr_thres:
            tpr_cnt[wp] += 1

        # Multi-bit metrics
        # (extracted already deserialized above)
        if len(extracted) > 0:
            ba = bit_accuracy(extracted, gt_bits)
            if ba is not None:
                bit_acc_list[wp].append(ba)
            ma = full_message_accuracy(extracted, gt_bits)
            if ma is not None:
                msg_acc_list[wp].append(ma)

        # Embedding efficiency: bits embedded per high-entropy token
        total_embedded_bits = len(extracted)
        total_high_entropy_tokens = len(match_flags)
        if total_high_entropy_tokens > 0:
            bits_per_tok_list[wp].append(total_embedded_bits / total_high_entropy_tokens)

    # Write results
    output_lines = []
    for wp in sorted(tot_cnt.keys()):
        T = tot_cnt[wp]
        output_lines.append("=" * 80 + "\n")
        output_lines.append(f"Watermark: {wp}\n")
        output_lines.append(f"Total samples: {T}\n")
        output_lines.append("\n--- Zero-bit Detection ---\n")
        output_lines.append(f"Median p-value: {np.median(p_value_list[wp]):.6f}\n")
        output_lines.append(f"TPR @ FPR={fpr_thres}: {tpr_cnt[wp] / T:.4f}  ({tpr_cnt[wp]}/{T})\n")

        output_lines.append("\n--- Multi-bit Message Extraction ---\n")
        if len(bit_acc_list[wp]) > 0:
            output_lines.append(f"Per-bit accuracy (mean ± std): "
                                 f"{np.mean(bit_acc_list[wp]):.4f} ± {np.std(bit_acc_list[wp]):.4f}\n")
        else:
            output_lines.append("Per-bit accuracy: N/A (no bits extracted)\n")

        if len(msg_acc_list[wp]) > 0:
            output_lines.append(f"Full-message accuracy: "
                                 f"{np.mean(msg_acc_list[wp]):.4f}  ({int(sum(msg_acc_list[wp]))}/{len(msg_acc_list[wp])})\n")
        else:
            output_lines.append("Full-message accuracy: N/A\n")

        if len(bits_per_tok_list[wp]) > 0:
            output_lines.append(f"Bits per high-entropy token (mean): "
                                 f"{np.mean(bits_per_tok_list[wp]):.3f}\n")
        else:
            output_lines.append("Bits per token: N/A\n")

    with open(save_path, "w") as f:
        f.writelines(output_lines)

    # Also print to stdout
    print("".join(output_lines))


def get_save_path(score_path, fpr_thres, len_limit):
    save_dir  = "./results"
    info_path = "/".join(score_path.split("/")[-4:-1])
    file_name = (
        score_path.split("/")[-1].split(".")[0]
        + "_adamc_eval_"
        + str(fpr_thres).replace(".", "_")
        + "_"
        + str(len_limit)
        + ".txt"
    )
    return os.path.join(save_dir, info_path, file_name)


def main():
    parser = argparse.ArgumentParser(
        description="Evaluate AdaMC watermark: zero-bit detection + multi-bit extraction."
    )
    parser.add_argument("--score_path", type=str, required=True,
                        help="Path to score.txt produced by evaluate_watermark_score.py")
    parser.add_argument("--fpr_thres", type=float, default=0.001,
                        help="FPR threshold for TPR calculation. Default: 0.001")
    parser.add_argument("--len_limit", type=int, default=50,
                        help="Minimum text length (# high-entropy tokens) to include. Default: 50")
    parser.add_argument("--message_hex", type=str, default=None,
                        help="Ground-truth message as hex string (e.g. '9a3bf201').")
    args = parser.parse_args()

    save_path = get_save_path(args.score_path, args.fpr_thres, args.len_limit)
    save_dir  = "/".join(save_path.split("/")[:-1])
    os.makedirs(save_dir, exist_ok=True)

    generate_result(
        score_path=args.score_path,
        save_path=save_path,
        fpr_thres=args.fpr_thres,
        len_limit=args.len_limit,
        message_hex=args.message_hex,
    )
    print(f"\nResults saved to: {save_path}")


if __name__ == "__main__":
    main()
